name = "picky-eater-preview"
pages_build_output_dir = "."
compatibility_date = "2026-09-20"

[vars]
AUTH_FROM_EMAIL = "Food My Way <login@foodmyway.app>"
AUTH_ORIGIN = "https://foodmyway.app"

[[d1_databases]]
binding = "LEADS"
database_name = "food-my-way-leads"
database_id = "86cfba25-a029-4b4e-9612-86325b11db73"

[[d1_databases]]
binding = "PURCHASES"
database_name = "food-my-way-purchases"
database_id = "fe02092f-41c3-4ac4-b4b5-2b5e8c22fc23"

[[d1_databases]]
binding = "TELEMETRY"
database_name = "food-my-way-telemetry"
database_id = "ea353c89-a43a-4918-aa01-2a97d543c575"

[[d1_databases]]
binding = "ACCOUNTS"
database_name = "food-my-way-accounts"
database_id = "832f6e5b-5907-4aa4-987c-27b1ac4896de"
